### PR TITLE
removed extraneous files

### PR DESCRIPTION
**Pull request by achung205**

### CODE REVIEW

**Comment by achung205** [comment]
script not showing up on sdn

**Comment by Strikegently** [comment]
You do know that this commit removes your script, right?

**Comment by achung205** [comment]
i have a folder named Agility and my source files are in there. i removed the files from the andyroo/ directory. does that not work? what if i want to make another script?

**Comment by Strikegently** [comment]
@achung205 
I didn't see that. All I saw was that it removed your script.

Merged.

**Pull request merged**
