### PR TITLE
Scripts

### PR DESCRIPTION
**Pull request by armark1ng**
Link to thread: http://www.powerbot.org/community/topic/1323639-osrs-armars-shop-items-auto-buyer/
Profile : https://www.powerbot.org/community/profile/538930-armark1ng/

A pull request for shop items auto buyer script.

### CODE REVIEW

**Comment by Strikegently** [comment]
Please double check the guidelines for submission.

**Comment by armark1ng** [comment]
I made sure to follow them all.

**Comment by armark1ng** [comment]
just corrected the properties sorry i thought i did the first time

**Comment by Strikegently** [comment]
merged

**Pull request merged**
