### PR TITLE
WASD Camera Turning

### PR DESCRIPTION
**Pull request by xXTheAwesomerXx**
Adds support for using the WASD keys instead of the directional keys to change the angle and pitch of the camera.

### CODE REVIEW

**Comment by ChrisBPB** [comment]
really the existing methods should be changed to call the new version i.e 
`public boolean pitch(final int percent) {
pitch(percent, false);
}`


to reduce duplicate code without breakages

**Comment by Strikegently** [comment]
Are there any scenarios in which you can't use WASD keys?

**Comment by xXTheAwesomerXx** [comment]
@Strikegently If legacy interface mode and/or the chat always on feature is enabled then wasd will be typed into the chatbox; when legacy interface mode is turned on it switches chat always on to enabled by default. The purpose of this feature into the API would be for developers who wish to have the option to use WASD (I personally use WASD when moving the camera but recently figured that the bot uses directional)

**Comment by ChrisBPB** [comment]
Chat always on varpbit is (off to on)
1775 - 0 (0x0 -> 8 (0x8)

it is also the same when you turn legacy interface on, so you should use this to check if wasd is appropriate

**Comment by Strikegently** [comment]
Make sure these scenarios are accounted for.

**Comment by xXTheAwesomerXx** [comment]
I believe the varpbit for always on chat changes depending on legacy interface

**Comment by ChrisBPB** [comment]
there are other ones that change for the legacy interface but 1775 still changes to 8 from when I tested

**Comment by xXTheAwesomerXx** [comment]
[12:59:45] 1775 - 1024 (0x400) -> 1032 (0x408)
[12:59:49] 1775 - 1032 (0x408) -> 1024 (0x400)
That's what I got using legacy interface and rs3 interface

**Comment by ChrisBPB** [comment]
8 still appears to be the common factor, you could probably sort it with a mask still

@ArtificialPB might know more

**Comment by xXTheAwesomerXx** [comment]
Methods should work flawlessly now

**Comment by Strikegently** [comment]
what is:
`if ((ctx.varpbits.varpbit(1775) >> 3 & 0x1) == 1)`

?

**Comment by ChrisBPB** [comment]
check for chat always on

**Comment by Strikegently** [comment]
Put this in its own method, under `Game` to improve code readability and maintainability.

**Comment by xXTheAwesomerXx** [comment]
Added said method to the Game class and updated the Camera class to use that method

**Comment by Strikegently** [comment]
` tx.input.send(up ? useWasd ? "{VK_W down}" : "{VK_UP down}" : useWasd ? "{VK_S down}" : "{VK_DOWN down}"); `

Could you clean these up?
Nested ternaries are incredibly cumbersome to read.

**Comment by xXTheAwesomerXx** [comment]
Sorry for the delayed response code should be optimized for readability.

**Pull request merged**
