### PR TITLE
Granite Splitter and multiple starter projects

### PR DESCRIPTION
**Pull request by superchaoran**
https://www.powerbot.org/community/topic/1311676-application05mhgranite-splitter-ultimate/

### CODE REVIEW

**Comment by Strikegently** [comment]
Your scripts each need a topic ID.

**Comment by superchaoran** [comment]
I have 5 folders, each represents a project, currently i have published BananaFiller and GraniteSplitter is waiting to be published. Both of them have topic ID attached. Rest 3 folders are just starter projects, not posted on forum yet. Could you please help me publish GraniteSplitter? Thanks!

**Comment by Strikegently** [comment]
If you don't want to publish the other 3 scripts, then don't include them in your commits.

**Comment by superchaoran** [comment]
Removed 3 other unpublished projects. Please help me merge and publish topic 1311676.
https://github.com/superchaoran/powerbot/tree/scripts/src/superchaoran
Thanks. Sorry for the long commits. I will use rebase -i next time.

**Pull request merged**
