### PR TITLE
Avoids trying to open equipment tab if bank is open

### PR DESCRIPTION
**Pull request by ArtificialPB**
Title

### CODE REVIEW

**Comment by ArtificialPB** [comment]
Fixed an issue with Hud#opened() in legacy mode where it would try to open the LegacyTab instead of just checking if it's opened.

**Comment by Timer** [comment]
Nice catch, @ArtificialPB

**Comment by Timer** [comment]
@ArtificialPB can you please rebase and remove your edits to the imports?

**Comment by ArtificialPB** [comment]
@Timer Fixed imports

**Comment by Timer** [comment]
Thanks!

**Pull request merged**
