### PR TITLE
Set script to hidden

### PR DESCRIPTION
**Pull request by xXTheAwesomerXx**
This script is now only for new developers to view the code

### CODE REVIEW

**Comment by Strikegently** [comment]
If it isn't going to be on the SDN, then upload the script to your personal repository.

**Comment by xXTheAwesomerXx** [comment]
I don't want it to be on the SDN at all, I just wanted to give aspiring developers something to compare against? Should I just remove it from the OSR all together?

**Comment by Strikegently** [comment]
This repo is specifically for people to upload their scripts to the SDN. If the script is not going to be on the SDN, then upload it to your own personal Github repo and post the link on the project thread.

**Comment by xXTheAwesomerXx** [comment]
Aha makes sense thanks :)

**Pull request closed without merging**
