### PR TITLE
Readability and formatting consistency updates for Elder

### PR DESCRIPTION
**Pull request by Strikeskids**
Changed variables names to become more descriptive.
Fixed broken-logic segments.
Improved randomization logic.
Removed some null-pointer bugs.
Switched from integer to enum state transitions.

### CODE REVIEW

**Comment by Strikegently** [comment]
I won't make changes to a script without the author's consent, but feel free to send this to him.

**Comment by Strikeskids** [comment]
I'm a bit confused. I thought the whole point of this repo was so that people can contribute to each other's scripts.

**Comment by Strikegently** [comment]
You may "fork" someone's script to make modifications for release, but you can't change the author's source directly without their consent.

**Comment by Timer** [comment]
@Strikegently  I thought anyone was allowed to edit another person's script per
>... anyone else can view and edit your code. Any submissions and changes will be approved by the admins ...

**Comment by Timer** [comment]
@Strikeskids nice to see you again

**Comment by Strikegently** [comment]
@Timer 
It is correct that anyone can edit your script, but I see a difference between editing, and completely modifying the structure of, someone's work.

**Comment by Timer** [comment]
Script author
>you can accept the changes it looks good

**Comment by Strikegently** [comment]
Merged.

**Pull request merged**
