### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by achung205**
http://www.powerbot.org/community/topic/1298690-agility/

### CODE REVIEW

**Comment by Strikegently** [comment]
Your script name and description need to be more appropriate.

**Comment by achung205** [comment]
are these changes that i must make for you to merge my commit?

**Comment by ChrisBPB** [comment]
Yes as we don't want 'poopsicle' on the SDN

**Comment by achung205** [comment]
sorry i forgot that the script name is how it appears on the script repo :)

**Comment by Strikegently** [comment]
The description is what shows on the SDN, so a better description means that the user is more likely to find your script based on what they search for.

**Comment by Strikegently** [comment]
Merged. In the future, please make your Pull Request titles more descriptive; to at least include the script name and your commit purpose.

**Pull request merged**
