### PR TITLE
Added additional rt6 item parameters

### PR DESCRIPTION
**Pull request by ArtificialPB**
Added additional rt6 item parameters requested in https://github.com/powerbot/powerbot/issues/887

### CODE REVIEW

**Comment by Timer** [comment]
Thanks! I was working on the same thing then saw this PR.

**Comment by Timer** [comment]
Your request was merged cleanly via commit 1a6128fe3c0604dce9cc2c8d99d830e749bf3687.
Simply delete your `newbranch` and bring `rsbot-api` up to date with upstream for future changes.
I saw you already merged your `newbranch` into `rsbot-api`, to resolve this just do `git checkout rsbot-api`, `git reset --hard HEAD~1`, `git fetch powerbot`, `git merge powerbot/rsbot-api --ff-only`, `git push -f`.

**Comment by Timer** [comment]
@ArtificialPB what about feature parity for old school and ground items?

**Comment by ArtificialPB** [comment]
Thanks for the info about git.

I'll add osrs and some other rs3 parameters and add GenericItem to rt4.

**Pull request closed without merging**
