### PR TITLE
first release of script

### PR DESCRIPTION
**Pull request by noobienoobie123**
topic - 1335353
releasing Lumbridge Killer script

### CODE REVIEW

**Comment by Strikegently** [comment]
1. This won't compile because your package declarations don't match the actual structure;
2. You need to have a valid topic ID in your manifest;

**Comment by noobienoobie123** [comment]
Hi, what do you mean my package declarations don't match the actual structure?

**Comment by noobienoobie123** [comment]
Also I just added the topic id to my manifest how do I re upload to github?

**Comment by rs-sliske** [comment]
your package declarations (first line of each file) needs to match the directory structure relative to src

**Comment by noobienoobie123** [comment]
Hi, I have changed my package declarations, how do I delete my previous folder of NoobieNoobieSlayer from my folder in the src and add my new files?

**Pull request merged**
