### PR TITLE
Extra methods and new class

### PR DESCRIPTION
**Pull request by AnthonyOSX**
Combat/Prayer methods
Base DepositBox class

### CODE REVIEW

**Comment by iitc** [comment]
Good old .gitignore.

**Comment by AnthonyOSX** [comment]
@iitc You may want to update your guide to contributing to the API with a section regarding ignoring files. I had no idea that you could do per repository excludes using .git/info/excludes instead of a .gitignore.

**Comment by Timer** [comment]
https://github.com/powerbot/powerbot/pull/1137/files#diff-04d519b30759ed392d1bd019c42f466fR97

**Comment by AnthonyOSX** [comment]
One second l0l

**Comment by AnthonyOSX** [comment]
Done

**Comment by Timer** [comment]
spanks.

**Pull request closed without merging**
