### PR TITLE
Adding bananna grabber

### PR DESCRIPTION
**Pull request by needscroll**
Thread here
https://www.powerbot.org/community/topic/1335857-sw-applicationdelay-for-2-daysno-reqs500khbanana-apple-and-grape-gathering-bot/

### CODE REVIEW

**Comment by Strikegently** [comment]
This doesn't compile.

**Comment by needscroll** [comment]
That's strange.
I just downloaded the files and it seems to work fine for me.
Are there any changes that I'm suppose to make for the script to run on the SDN aside from what I have already done?
I will make a thread in the developers section for more help.

**Comment by Strikegently** [comment]
You declared `package Tasks; `
The actual package is
`needscroll/BanannaGrabber/Tasks/Antiban.java`

This won't compile.

**Comment by needscroll** [comment]
Package has been updated

**Comment by Strikegently** [comment]
You know you don't need to do a commit-per-file, right?

**Pull request merged**
