### PR TITLE
first upload SalmonCollector

### PR DESCRIPTION
**Pull request by turningwind**

### CODE REVIEW

**Comment by Strikegently** [comment]
Please rename your main script class something other than "Main".

**Comment by turningwind** [comment]
Changed it, may I know the reason for this?

**Comment by Strikegently** [comment]
This won't compile. The file is named SalmonCollector but the class is still named Main.

>Changed it, may I know the reason for this?
Scripts on the SDN are identified by user ID and main script class name. All Open SDN™ scripts are uploaded to a sandbox account; naming the main class something incredibly generic like "Main" increases the likelihood of conflicts.

**Comment by turningwind** [comment]
I understand, I will make sure to keep that in mind for my next scripts. Thanks for explaining.

**Pull request merged**
