### PR TITLE
CrazeFisher Initial SDN Request.

### PR DESCRIPTION
**Pull request by alexm118**

### CODE REVIEW

**Comment by Strikegently** [comment]
1. JForm Designer files won't work on the SDN
2. Don't commit your class files - just your source code

**Comment by alexm118** [comment]
@Strikegently 

Thanks, Removed the class files and the JFormDesigner. Also removed the shop buying script because it is bombing my build for using 1.7 features. Ammended my .gitignore, we may want to have a global gitignore if we don't already.

**Comment by Strikegently** [comment]
why are you removing other people's scripts?

**Comment by alexm118** [comment]
Because it doesn't make sense to have a script that isn't compatible or working on the SDN.

**Comment by Strikegently** [comment]
What 1.7 features was it using?

**Comment by alexm118** [comment]
<> within his GUI to identify types.

**Comment by Strikegently** [comment]
So make a another PR to fix it; don't just remove his scripts.

**Comment by alexm118** [comment]
Why should I be fixing someone elses scripts? I wouldn't want or expect anyone else to be fixing my scripts and we shouldn't be hosting broken scripts on the SDN.

**Comment by Strikegently** [comment]
>Why should I be fixing someone elses scripts? 
That's like 30% of the reason of open source software.

**Comment by Strikegently** [comment]
If you're going to modify someone else's script, then do so in a separate PR.

**Pull request closed without merging**
