### PR TITLE
Scripts

### PR DESCRIPTION
**Pull request by xXTheAwesomerXx**
Added DBWoodcutter and DBFisher

### CODE REVIEW

**Comment by iitc** [comment]
Why do you have the api as a remote of your scripts? You should be using public rsbot releases to compile against.

**Comment by xXTheAwesomerXx** [comment]
If I did this incorrectly it's because I'm not entirely sure on how I should upload the scripts themselves to the pubic SDN. Is there any way you can instruct me on doing so?

**Comment by Timer** [comment]
@xXTheAwesomerXx join slack for help https://powerbot.herokuapp.com/

**Comment by Strikegently** [comment]
@xXTheAwesomerXx 
We have instructions for this very reason.

https://github.com/powerbot/powerbot/tree/scripts

**Comment by xXTheAwesomerXx** [comment]
I followed the steps but I kept getting a permission error

**Pull request closed without merging**
