### PR TITLE
zPKHelper initial release

### PR DESCRIPTION
**Pull request by ElZaiat**
Thread: https://www.powerbot.org/community/topic/1331392-osrs-zpkhelper/

### CODE REVIEW

**Comment by Strikegently** [comment]
This seems more like an OSBuddy plugin than an RSBot script.

**Comment by ElZaiat** [comment]
Does that seem to be a problem? Anyway, I will be adding features like Auto K.O and Auto Eat in the future.

**Comment by Strikegently** [comment]
PKing a competitive event in RuneScape. Features like those seem like they would give the user an unfair advantage against a human.

**Comment by ElZaiat** [comment]
Isn't the bot's purpose to give users unfair advantage 0.o?

**Comment by Strikegently** [comment]
Not in direct competition with other players, no.

**Pull request closed without merging**
