### PR TITLE
Remove costs from LocalPath

### PR DESCRIPTION
**Pull request by tanlines**
The original `getCosts` seemed to be trying to increase the cost of tiles around obstacles and boundaries. This is a bad idea since it would make paths avoid walking next to walls.
HOWEVER
The original `getCosts` was broken and would add random values for every tile.

Removing the costs altogether made the method stable and also increased speed significantly, see [difference in paths](https://imgur.com/a/GpYYxjs). Since this is used for calculating distance, it should not be randomised.

The previous map offset also always returned 0, the working method is `ctx.game.mapOffset()`.
`getNode` was updated in light of this change. The two classes that call `getNode` already get the offset from `ctx.game.mapOffset()`.

### CODE REVIEW

**Comment by Smileynator** [comment]
The point of the random cost, might have been to encourage behaviour that is not consistent every time (aka: anti measures for banning) which might be undesired to be removed. I can imagine there is a big gain to be made between 1ms and 70ms though.

**Comment by tanlines** [comment]
@Smileynator Should be handled on a script by script basis. No point randomising all the points between you and your destination when you're just going to click your destination and let the game path find itself.

**Comment by Smileynator** [comment]
Fair point :+1:

**Comment by ChrisBPB** [comment]
This is done because if you click around many obstacles your waypoint market will be reset which causes odd behaviour in scripts

**Pull request closed without merging**
