### PR TITLE
J333

### PR DESCRIPTION
**Pull request by jps333**
New pull request for https://www.powerbot.org/community/topic/1341312-rs3-general-smithing-free-99/

If the files do not compile please let me know what the errors are so I can fix the problem. The GUI code only depends on standard java packages and everything is compiling fine on my end.

### CODE REVIEW

**Comment by Strikegently** [comment]
Don't close a Pull Request then open a new one each time a change is requested. Commit your changes to your branch - the PR will update.

**Comment by jps333** [comment]
1. The first time I had accidentally created a branch with my github username rather than my powerbot username. I thought that might be a problem so I changed the branch name and the old PR was automatically closed. I'll make sure not to close this PR though.

2. Alright, I'll add one when I get the chance.

Out of curiosity, will it be a problem if I have multiple packages rather than just the j333/scripts packages? For instance, I've added the source code to a library that I'd like to use in a package outside of scripts package but still within my username package (e.g. J333/gson). I'm using gson to aid in serializing mediawiki content.

**Comment by jps333** [comment]
*deserializing

**Comment by Strikegently** [comment]
1. Branch name doesn't matter. It all gets merged into `scripts`
2. You can have whatever structure you'd under your username. Java 8 added support for JSON parsing, so you don't really need a third-party library for that.

**Comment by jps333** [comment]
Oh, right on. I did not know that.

**Pull request merged**
