### PR TITLE
AlKharid Tanner

### PR DESCRIPTION
**Pull request by awbasham**

### CODE REVIEW

**Comment by Strikegently** [comment]
Don't name your main script class `Main`. The SDN identifies scripts by user ID and class name, so something more meaningful would be best.

**Comment by awbasham** [comment]
@Strikegently Should be fixed now.

**Comment by Strikegently** [comment]
I would also encourage you to make more meaningful commit messages.  "Quickfix" is a meaningless message that just clutters your history and makes it difficult to find a particular commit you are looking for.

**Comment by awbasham** [comment]
I normally would, but they were literally "quick fixes". As in I refactored the Main.class file and it messed up a bunch of strings for some reason.

**Pull request merged**
