### PR TITLE
GrandExchangeAlcher Script Item Server IP

### PR DESCRIPTION
**Pull request by ChrisHemmens**
Changed the IP address of the items server. Script should now work again.

### CODE REVIEW

**Comment by Strikegently** [comment]
1. Why are you hardcoding the IP?
2. You have merge conflicts that need resolved.

**Comment by ChrisHemmens** [comment]
1. I don't have a domain name.
2. What are the conflicts?

**Comment by Strikegently** [comment]
Github doesn't show the merge conflicts, but you should be able to pull to resolve them.

**Comment by ChrisHemmens** [comment]
I'm not getting any conflicts when I pull. :confused:

**Comment by Strikegently** [comment]
Did you push to update your repo?

**Comment by ChrisHemmens** [comment]
Yes

**Comment by Strikegently** [comment]
"This branch is 3 commits ahead, 58 commits behind powerbot:scripts."

Fetch, rebase, push to your repo.

**Comment by ChrisHemmens** [comment]
Try that.

**Comment by Strikegently** [comment]
It'll merge, but you just re-committed basically your entire history.

**Comment by ChrisHemmens** [comment]
Yeah, i don't know what happened. It completely messed up on my end.

**Pull request closed without merging**
