### PR TITLE
Add worldID filter

### PR DESCRIPTION
**Pull request by turningwind**

### CODE REVIEW

**Comment by Strikegently** [comment]
Rather than adding an arbitrary id filter, fit it into the appropriate architecture.

https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/Identifiable.java

**Comment by turningwind** [comment]
@Strikegently Sorry for my ignorance. Are the new changes what you were looking for?

**Comment by Strikegently** [comment]
I meant make Worlds an Id Query and override its methods to keep it polymorphic and consistent with the API.

**Comment by turningwind** [comment]
@Strikegently I'm not quite sure what's wrong with the default method implementations, what functionality does there need to be added by overriding?

**Comment by Strikegently** [comment]
Nothing - should be fine.

**Pull request merged**
