### PR TITLE
adding iSmithing

### PR DESCRIPTION
**Pull request by aliriomendezjr**
This is a F2P Bar Smithig:

 

Bars allowed:

Bronze
Iron
Silver
Steel
Gold
Mithril
Adamantite
Runite
 

When you run the script it displays an input dialog with a select-option. 

Script will know how much Ore you need to have to do your selected bar e.g (Runite: 1 Runite Ore x  8 Coal = 24 Coal and 3 Runite Ore)

Tested in: Al Kharin (recommend place) and Falador.

Recommendation:  Start near bank.

 

Any sugestion is allowed.

### CODE REVIEW

**Comment by Strikegently** [comment]
This won't compile. Your package structure isn't correct.

**Comment by aliriomendezjr** [comment]
Sorry, check now please.

**Comment by Strikegently** [comment]
Please re-read the instructions. You need a topic ID, otherwise your script won't show up on the SDN.

https://github.com/powerbot/powerbot/tree/scripts

**Comment by aliriomendezjr** [comment]
Done

**Pull request merged**
