### PR TITLE
Additional rt4 and rt6 parameters

### PR DESCRIPTION
**Pull request by ArtificialPB**
RT6:
* Equipped actions
* Bank actions (actions in inventory when bank is open)

RT4:
* Added GenericItem and added getter methods for some parameters

### CODE REVIEW

**Comment by Timer** [comment]
Merged cleanly in bed53137cb53424445c5e86168628fd2bd7c42dc.
I noticed you didn't follow my git commands!

**Comment by ArtificialPB** [comment]
I did follow your commands but one of them did not work and I've additionally messed something up. I apologize for any inconvenience this has caused, I'm a bit new to using git in collaborations.

**Comment by Timer** [comment]
@ArtificialPB no it doesn't cause me any inconvenience I just have to cherry-pick commits and then you have a mess in your branch.

**Comment by ArtificialPB** [comment]
I believe I've sorted it out now @Timer

**Pull request closed without merging**
