### PR TITLE
Hauntbrave

### PR DESCRIPTION
**Pull request by everettyang**
Added other scripts

### CODE REVIEW

**Comment by Strikegently** [comment]
Is your powerbot username "everett" or "hauntbrave"?

**Comment by everettyang** [comment]
My powerbot username is hauntbrave. Everettyang is my github username.

**Comment by Strikegently** [comment]
So the author attribute should be hauntbrave.

**Comment by everettyang** [comment]
Oh right, I guess I forgot to change it for some of them. Ill do it in a
bit.

**Comment by everettyang** [comment]
Okay, I changed it.

**Comment by Strikegently** [comment]
Your scripts must have a valid topic; otherwise, they won't appear on the SDN.

**Comment by everettyang** [comment]
Ok, I believe all of them should have a topic associated now.

**Comment by Strikegently** [comment]
In the future, when adding multiple scripts, each should have their own pull request, and your PR titles should be meaningful.

**Comment by everettyang** [comment]
Okay, Ill keep that in mind. For some reason, only one of my scripts shows
up on the SDN. Why is that?

**Pull request merged**
