### PR TITLE
Ourunia

### PR DESCRIPTION
**Pull request by Dragas**
An ourania runner script. See [thread](https://www.powerbot.org/community/topic/1345732-osrs-ourunia/)

### CODE REVIEW

**Comment by Strikegently** [comment]
Remove the .idea encoding file.

**Comment by Dragas** [comment]
@Strikegently done

**Comment by Strikegently** [comment]
Your package names should start with your powerbot username if you want it to be on the Open SDN.
You can use whatever you want if you put it on your private powerbot repo (if you want to apply for SW).

**Comment by Dragas** [comment]
Isn't that against java naming conventions? 🤔

**Pull request merged**
