### PR TITLE
Update bank to add escape closing

### PR DESCRIPTION
**Pull request by Mkerian10**
Adds a method for closing the bank with escape, also checking for escape closing to be active.

### CODE REVIEW

**Comment by Strikegently** [comment]
Shouldn't it wait for the bank to close?

**Comment by Mkerian10** [comment]
@Strikegently It's been updated, that was a silly mistake by me. I'm not sure if the API doesn't allow lambdas for some reason because most of the code is in anon form, just let me know and I can change it. Now it should properly check for a closed bank, and then close it with keys if it isn't. My only question is, right now the way I have it structured, if the Condition.wait() fails, it'll go to the default close() method. Would you rather just return false if the escape fails or have it manually close?

**Comment by Strikegently** [comment]
This won't compile.

**Comment by Mkerian10** [comment]
@Strikegently Why not? It's working fine on my machine.

**Comment by Mkerian10** [comment]
@Strikegently Should be fixed, dunce mistake

**Pull request closed without merging**
