### PR TITLE
I believe I fixed the problem.

### PR DESCRIPTION
**Pull request by ValintineLeroux**
Should compile now.

### CODE REVIEW

**Comment by Strikegently** [comment]
You removed other people's scripts in your commit... Don't do that.

**Comment by iitc** [comment]
Especially don't remove @strikegently's scripts. Lol

**Comment by ValintineLeroux** [comment]
Oh my bad I'm still getting familiar with github won't happen again

**Comment by ValintineLeroux** [comment]
I reverted that and pushed without removing anything this time

**Comment by Strikegently** [comment]
Merged.

**Pull request merged**
