### PR TITLE
Add an unreachable bank

### LINKED ISSUE #2062: Bank::getBank doesn't filter out "fake" banks.
**I found an issue in [`org.powerbot.script.rt4.Bank`](https://github.com/powerbot/powerbot/blob/rsbot-api/src/main/java/org/powerbot/script/rt4/Bank.java#L17)**

The `getBank` method searches for any GameObject called "Bank chest", "Bank Chest-wreck" or "Bank booth". Somehow Jagex managed to create "fake" or closed bank booths in some areas in the game. These are called "Bank booth" but they cannot be opened.

This means that if one of those "fake" banks is the nearest bank booth, the mouse will hover over the booth without clicking, as the script is looking for menu actions "Bank", "Use" or "Open" which are not present on it.

An example "fake" booth can be found in Draynor, see image below.
_This is a problem there, as it is the closest bank booth to the player if you are fishing shrimp or chopping willows._

Fake bank

### PR DESCRIPTION
**Pull request by OneBigOwnage**
Fixes #2062, the correct way.

### CODE REVIEW

**Comment by ChrisBPB** [comment]
sorry meant to reply yesterday, are you sure that's the right tile as those others aren't far away and I'm trying to picture what they could be in this context

**Comment by AshGreh** [comment]
@ChrisBPB filter by actions using a hash set instead

**Comment by OneBigOwnage** [comment]
I am certain that the tile I am adding in this PR is correct.
Using this code:
```java
public void repaint(Graphics graphics) {
    Tile[] existingTiles = new Tile[]{
        new Tile(3187, 3446, 0), new Tile(3088, 3242, 0),
        new Tile(3096, 3242, 0), new Tile(3096, 3241, 0), new Tile(3096, 3245, 0),
    };

    graphics.setColor(Color.CYAN);

    for (Tile tile : existingTiles) {
        graphics.drawPolygon(tile.matrix(ctx).bounds());

        graphics.drawString(String.format("(%s, %s)", tile.x(), tile.y()), tile.matrix(ctx).centerPoint().x - 30, tile.matrix(ctx).centerPoint().y);
    }

    Tile myTile = new Tile(3091, 3241, 0);

    graphics.setColor(Color.YELLOW);
    graphics.drawPolygon(myTile.matrix(ctx).bounds());
    graphics.drawString(String.format("(%s, %s)", myTile.x(), myTile.y()), myTile.matrix(ctx).centerPoint().x - 30, myTile.matrix(ctx).centerPoint().y);
}
```
Will result in this image:
Tiles


The yellow tile is my addition.

**Comment by OneBigOwnage** [comment]
I would like to add that you can see in the last picture that there is another unreachable bank in here, the 2nd one from the left.
That one is called "Closed bank booth" so it doesn't get picked up and is thus not an issue.

**Comment by AshGreh** [comment]
Code looks acceptable. @OneBigOwnage could you show a picture of banks the latest filter filters out?

**Comment by OneBigOwnage** [comment]
The proposed solution had a bug as the first option of a bank could be `null` and for NPC banks it is "Talk-to" in most cases. Solved it by using a `Collections.disjoint()`.

Using this snippet in a polling script:
```java
public static final Tile[] CONSTANTS_BANK_UNREACHABLES = new Tile[]{
        new Tile(3187, 3446, 0), new Tile(3088, 3242, 0),
        new Tile(3096, 3242, 0), new Tile(3096, 3241, 0),
        new Tile(3096, 3245, 0), new Tile(3091, 3241, 0),
};

private static final Set<Tile> BANK_UNREACHABLES = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(CONSTANTS_BANK_UNREACHABLES)));
private static final Set<String> BANK_ACTIONS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList("Bank", "Use", "Open", "bank", "use", "open")));

private static <T extends Locatable & Actionable> boolean UNREACHABLE_FILTER(T entity) {
    return !BANK_UNREACHABLES.contains(entity.tile()) && !Collections.disjoint(BANK_ACTIONS, Arrays.asList(entity.actions()));
}

@Override
public void repaint(Graphics graphics) {
    graphics.setColor(Color.PINK);

    ctx.npcs.select().name(Constants.BANK_NPCS).select(TestScript::UNREACHABLE_FILTER).nearest()
            .forEach(t -> graphics.drawPolygon(t.tile().matrix(ctx).bounds()));

    ctx.objects.select().name(Constants.BANK_BOOTHS, Constants.BANK_CHESTS).select(TestScript::UNREACHABLE_FILTER).viewable().nearest()
            .forEach(t -> graphics.drawPolygon(t.tile().matrix(ctx).bounds()));
}
```

I was able to create this picture:
image

**Comment by ChrisBPB** [comment]
would it be better to use ignore case instead of doing more loops?

**Comment by AshGreh** [comment]
@ChrisBPB which loops are we talking about?

**Pull request merged**
