### PR TITLE
Fix and Script release

### PR DESCRIPTION
**Pull request by ValintineLeroux**
Fixed banking in NewbHonies
Releasing FreeWorld Chopper

### CODE REVIEW

**Comment by Strikegently** [comment]
You need to add a proper topic ID for your script.

**Comment by ValintineLeroux** [comment]
oh I put it on the wrong script 

    On Saturday, January 2, 2016 6:40 PM, Strikegently <notifications@github.com> wrote:
 

 You need to add a proper topic ID for your script.—

**Comment by ValintineLeroux** [comment]
Added the proper ID

**Comment by Strikegently** [comment]
Merged.

**Pull request merged**
