### PR TITLE
Added Outrage Chicken Slayer V1.0

### PR DESCRIPTION
**Pull request by OutrageHost**
Added Outrage Chicken Slayer!

http://www.powerbot.org/community/topic/1304601-rs3-outrage-chicken-slayer/

Thanks!

### CODE REVIEW

**Comment by Strikegently** [comment]
Please read the OSR guidelines.

https://github.com/powerbot/powerbot/blob/scripts/README.md

**Comment by OutrageHost** [comment]
Im not sure whats missing? Im sure i added everything thats needed?

**Comment by rs-sliske** [comment]
you need to fix your packages

**Comment by OutrageHost** [comment]
I think that fixed it!

**Comment by Moosheplusplus** [comment]
@OutrageHost your package must be <your username>.<script>, for example, src/mooshe/afk/ should be resembled as `package mooshe.afk;`, and your should be `outragehost.chicken`, or something similar to that.

**Comment by OutrageHost** [comment]
Hopefully that fixed it :D

**Comment by Moosheplusplus** [comment]
@OutrageHost your file structure has to match it too. Change your `src/Outrage Host/OutrageChickenslayer` to `src/outragehost/chicken/`

**Comment by OutrageHost** [comment]
@Moosheplusplus Thanks a lot for your help :D Hopefully this is it!

**Pull request merged**
