### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by iitc**
Began class header documentation (50% done) and managed to completely fill in a few small query and general interfaces.

### CODE REVIEW

**Comment by Timer** [comment]
Wow, nice going.

**Comment by Timer** [comment]
Can you rebase please?

**Comment by Timer** [comment]
@iitc let me know if you'd prefer me to rebase this (and have the `with Timer` appear)

**Comment by iitc** [comment]
@timer, I'll rebase here in a bit.

**Comment by Timer** [comment]
@iitc okay, it merge conflicts because I removed a class -- should be an easy fix

**Comment by Timer** [comment]
04b4994d08bdb5ee438517a019d34b28f9896368

**Pull request closed without merging**
