### PR TITLE
Initial add of script.

### PR DESCRIPTION
**Pull request by IntenseChanging**
Let me know if there's anything else I need to do.

### CODE REVIEW

**Comment by rs-sliske** [comment]
you package declaration needs to match the directory structure

**Comment by IntenseChanging** [comment]
My latest commit should have fixed that.

**Comment by Strikegently** [comment]
You should probably change the header to "@author: Coma"
It's literally a line-by-line copy with changed IDs.

https://www.powerbot.org/community/topic/1280609-the-rsbot-cookbook-writing-your-second-script/

**Comment by IntenseChanging** [comment]
Yes, I did base the script off that tutorial. I've just started making scripts, so I need something to base my code on. Added credit in my latest commit. More feedback is welcome.

**Pull request merged**
