### PR TITLE
Scripts

### PR DESCRIPTION
**Pull request by armark1ng**
i couldnt find my script on sdn so i figured that you cant put spaces between properties 
just removed the spaces and added an if.

### CODE REVIEW

**Comment by Strikegently** [comment]
You manifest has "OSRS" in it. Remove that; it's a filtered word.
Also you have merge conflicts. You need to pull master before merging your branch to push.

**Comment by armark1ng** [comment]
missclicked close

**Comment by Strikegently** [comment]
You need to resolve your merge conflicts.

**Comment by armark1ng** [comment]
I don't know whats causing it can you tell me how ?

**Pull request closed without merging**
