### PR TITLE
Initial release of gathering (working title)

### PR DESCRIPTION
**Pull request by TMKCodes**

### CODE REVIEW

**Comment by Strikegently** [comment]
Please read the instructions. 

https://github.com/powerbot/powerbot/tree/scripts

**Comment by TMKCodes** [comment]
Strikegently I did read the instructions? What did I do wrong?

**Comment by TMKCodes** [comment]
What I did was src/TMKCodes/Gathering/Gathering.java like src/Coma/claysoftener/Claysoftener.java

**Comment by ChrisBPB** [comment]
a folder isn't a package

**Comment by TMKCodes** [comment]
Fuck me. It meant the Java package name.

**Pull request merged**
