### PR TITLE
Added Tyskie's AIO TRuneCrafting

### PR DESCRIPTION
**Pull request by TyskieThijssen**
For more information check out: https://www.powerbot.org/community/topic/1334445-free-osrs-f2p-runecrafting-tyskies-aio-trunecrafting/

### CODE REVIEW

**Comment by Strikegently** [comment]
Read the instructions.

**Comment by TyskieThijssen** [comment]
@Strikegently Removed TPowerChop so only AIO TRuneCrafting is left. Sorry for the multiple scripts in one pull-request.

**Comment by Strikegently** [comment]
Re-read the instructions again.

>The parent package must be your powerbot username (e.g. coma/scripts/Script.java)

**Comment by ChrisBPB** [comment]
I have been merging them as I didn't think it mattered as long as he had his own folder so we knew it was his content, my bad.

Please update your scripts to conform to the written standards and we will merge them.

**Comment by rs-sliske** [comment]
think you will need to change your package declarations aswell

afaik they have to match the folder structure

**Pull request merged**
