### PR TITLE
Fixed spacing

### PR DESCRIPTION
**Pull request by 4ss4s1n**
Follow up of https://github.com/powerbot/powerbot/pull/1896

### CODE REVIEW

**Comment by 4ss4s1n** [comment]
I also think the logic can be applied inside the loop, start on [L44](https://github.com/powerbot/powerbot/blob/9a93564dab0889da8415193fd4b6126d8d1ded66/src/main/java/org/powerbot/bot/rt4/RandomEvents.java#L44).

**Comment by Strikegently** [comment]
You don't need to close a Pull Request when changes are requested. Push to your branch and the PR will update accordingly.

**Comment by 4ss4s1n** [comment]
@Strikegently thoughts on applying the logic inside the loop?

**Comment by 4ss4s1n** [comment]
@Strikegently thoughts on applying the logic inside the loop?

**Comment by Strikegently** [comment]
You seem to be over-complicating it. 
If an item is selected, deselect it.
If a spell is selected, deselect it.

That's really all you need.

**Comment by 4ss4s1n** [comment]
I personally think this is more readable. You shouldn't have to make a check for item being selected when you're not in the inventory. Yes, right now it's easy to have 2 cases, but in the future, as osrs keeps updating you may have trouble keeping up with all the cases. Also, this allows you to add more to each tab case specifically. I can roll it back to just checking the spell if you want, your call.

**Comment by Mkerian10** [comment]
@4ss4s1n But regardless you'll have to continue making cases in the future. Plus it's been like this for years, odds are it won't change significantly in the future.

**Pull request closed without merging**
