### PR TITLE
Update package structure

### PR DESCRIPTION
**Pull request by gabino75**

### CODE REVIEW

**Comment by Strikegently** [comment]
This has merge conflicts.

**Comment by gabino75** [comment]
Removed kebab-buyer altogether. Will re-merge after smither is on the SDN

**Comment by Strikegently** [comment]
1. Your script package structure needs to follow the guidelines
2. This still has merge conflicts

**Comment by gabino75** [comment]
How is the package structure supposed to look if you're trying to upload multiple different scripts? I'm looking at other user's SDN submissions and they seem to be identical.

**Comment by Strikegently** [comment]
Read the guidelines.
- The parent package _must_ be your powerbot username (e.g. coma/scripts/Script.java)

**Comment by Strikegently** [comment]
Closing from inactivity.

**Pull request closed without merging**
