### PR TITLE
Intial WoodChoppa commit

### PR DESCRIPTION
**Pull request by paregos**
Not sure if this is the correct format for creating pull requests into the open SDN.

Added the src files for my script under a new folder paregos/WoodChoppa/

Script chops and banks/drops logs in a number of locations.

### CODE REVIEW

**Comment by Strikegently** [comment]
1. What is your powerbot username? There are 3 different names in this project.
2. You need a valid topic ID.
3. This doesn't compile because of incorrect package declarations.

**Comment by paregos** [comment]
Opps sorry about that Ill close this and make another pull request after I fix it.

**Comment by Strikegently** [comment]
Don't make a whole other pull request for changes, just commit to your branch.

**Comment by Strikegently** [comment]
Comment when you're ready to have this re-opened.

**Pull request closed without merging**
