### PR TITLE
Rsbotupdate

### PR DESCRIPTION
**Pull request by Kyle628**

### CODE REVIEW

**Comment by Strikegently** [comment]
Few things:
- you don't need to call `ctx.controller.stop()` in your `stop` method. This method is only called when you stop the script, so stopping the script when it's stopping the script is unnecessary.
- Why are you clicking exact pixels in your `stop` method?

**Comment by Kyle628** [comment]
Oops, I will take that out.

I am clicking the exact pixels, because I first tried to logout using widgets, but I couldn't figure out how to click the "door" button. It doesn't have text so I couldn't find it in the widget explorer. I googled around, but couldn't find a logout method anywhere.

**Comment by Strikegently** [comment]
did you try `game.logout()`

**Comment by Kyle628** [comment]
In the docs I can only find game.loggedin() which just returns whether you or logged in or not.

ctx.game.logout();

throws me a cannot resolve method error

**Comment by rs-sliske** [comment]
`ctx.game.tab(Tab.LOGOUT)` should switch to that tab

**Comment by Kyle628** [comment]
Ooooh nice, that should help!

**Comment by Kyle628** [comment]
Okay, looks much better now using tabs and widgets

**Pull request merged**
