### PR TITLE
On demand item cache definition reading

### PR DESCRIPTION
**Pull request by ArtificialPB**
Requested in https://github.com/powerbot/powerbot/issues/1256. Item cache reading is now null safe.

I've also renamed ```boolean cert``` to ```boolean noted```.

### CODE REVIEW

**Comment by ArtificialPB** [comment]
Added rt4 null safe, on demand cache reading for items.

**Comment by Timer** [comment]
You really want this exposed. ;)

**Comment by ArtificialPB** [comment]
You have no idea how much time this is going to save me @Timer lol

**Comment by Timer** [comment]
thanks
6c853db939e7b717d9076fc4ec3ba6cdd7fcf096

**Comment by ArtificialPB** [comment]
Just noticed I forgot to make rt4 CacheItemConfig class public: https://github.com/powerbot/powerbot/blob/rsbot-api/rt4/CacheItemConfig.java#L13

**Comment by Timer** [comment]
695f6df

**Comment by ArtificialPB** [comment]
:+1: 
I saw you were looking for me on Slack. I'm a bit busy right now so if you need anything just send me a PM on the forums and I'll answer when I'm available.

**Pull request closed without merging**
