### PR TITLE
added brackets to case statements, fixed syntax error

### PR DESCRIPTION
**Pull request by achung205**
apparently there are compiler errors when running on the public repo. if possible, could i get the line numbers where these occur? i dont get compiler errors on my end. i am using java 6 with jdk1.8

### CODE REVIEW

**Comment by Strikegently** [comment]
You have merge conflicts that need resolved.

**Comment by achung205** [comment]
no idea what i did...why are all these previous commits appearing

**Comment by AnthonyOSX** [comment]
Use JDK 1.6, runtime doesn't matter.

**Comment by achung205** [comment]
please try merging. i believe the issue was due to package misnomer

**Comment by Strikegently** [comment]
why are there 40 duplicated, week-old commits?

**Comment by achung205** [comment]
i have no idea. i just executed the commands listed on the readme.md because there were branch conflicts and i didnt know how to fix them. then i re-added my files.

**Pull request closed without merging**
