### PR TITLE
Added rt4 keybind support

### PR DESCRIPTION
**Pull request by ArtificialPB**
Contains a check if ESC can be used for interface closing.

### CODE REVIEW

**Comment by ArtificialPB** [comment]
Tabs can now be opened with hotkeys, moved Keybind enum to the Game class.

**Comment by Strikegently** [comment]
Pinging @Moosheplusplus 
I don't play OSRS.

**Comment by rs-sliske** [comment]
@Strikegently neither does mooshe :p 

not had chance to check all the varpbit settings are correct etc, but overall process looks reasonable. osrs allows users to choose which f-key opens each interface. and as long as this doesnt end up with another dice roll i think it would be a useful thing to have

**Comment by Moosheplusplus** [comment]
@rs-sliske I imagine he pinged me because I previously proposed keybind support in the past on the forum, but I never submitted a PR.

**Pull request merged**
