### PR TITLE
Added Production Interface utilities

### PR DESCRIPTION
**Pull request by ArtificialPB**
Added utilities for interacting with Production Interface: http://runescape.wikia.com/wiki/Make-X

### CODE REVIEW

**Comment by Strikegently** [comment]
This seems like something that script writers should handle, not necessarily the API.

**Comment by ArtificialPB** [comment]
I think this will be an useful addition to the API and it will make script writing easier, especially for new users. This is like the Grand Exchange API. Why make everyone write their own API or copy it from snippets when it can be included in the RSBot API and be available from the start?

**Comment by Moosheplusplus** [comment]
Almost every preparation skill uses this interface, so I think it would be a valid addition for the RSBot API.

**Comment by Timer** [comment]
@Strikegently do you stand against not allowing this in or would it be a valid addition?

**Comment by ArtificialPB** [comment]
Solved conflicts with the base branch

**Pull request merged**
