### PR TITLE
Added AFK Wars

### PR DESCRIPTION
**Pull request by Moosheplusplus**

### CODE REVIEW

**Comment by Strikegently** [comment]
I can't see file changes currently, due to a Github issue. So this will be on hold until a solution is made.

**Comment by Timer** [comment]
@Strikegently just see https://github.com/Moosheplusplus/powerbot/tree/b279ec122c5069f7831cf2b02449211a4ebe6507/src/mooshe/afk

**Comment by Strikegently** [comment]
@Moosheplusplus 
- Remove resources\bg.png. Images can't be added to the SDN.
- rename "MainScript" to something more appropriate; scripts are identified by main class name.

**Comment by Moosheplusplus** [comment]
@Strikegently just to clarify, I just can't store it locally, or I can't use any image whatsoever?

**Comment by Timer** [comment]
@Moosheplusplus there is a separate place to upload images to the SDN, or just serve it from the internetz

**Comment by Moosheplusplus** [comment]
Alright, I renamed the main script class to IdleScript, and am now using downloadImage("https://i.imgur.com/qRolF87.png")

**Comment by Strikegently** [comment]
Merged.

**Pull request merged**
